subscribers:
  # Name all the topics to subscribe from in this section. You may also redefine the variable name
  # as long as you can load the yaml variable in your main file
  # imu_topic: "/wamv/sensors/imu/imu/data"
  # odom_topic: "/wamv/sensors/position/ground_truth_odometry"
  # # translation_odom_source_to_body: [-532.64,161.91,-0.07]
  # translation_odom_source_to_body: [-527.128,158.428,-0.085]
  # # rotation_odom_source_to_body: [0.877,-0.002,0.004,0.479]
  # rotation_odom_source_to_body: [0.875,0.002,-0.007,0.4808]
  imu_topic: "/wamv/sensors/imu/imu/data"
  odom_topic: "/wamv/sensors/position/ground_truth_odometry"
  translation_odom_source_to_body: [-532.64,161.91,-0.07] #for output.bag
  # translation_odom_source_to_body: [-527.127, 158.427, -0.085] #for circle.bag
  # translation_odom_source_to_body: [0, 0, 0]
  # rotation_odom_source_to_body: [0.877,-0.002,0.004,0.479]
  rotation_odom_source_to_body: [1, 0, 0, 0]

publishers:
  # Define publish rate and topics for publishers
  pose_publish_rate: 1000 # Hz
  pose_publish_topic: "/wamv/inekf_odom_correction/pose"
  pose_frame: "/map"

  path_publish_rate: 100 # Hz
  path_publish_topic: "/wamv/inekf_odom_correction/path"

  enable_slip_publisher: true